key="[REDACTED_PROD_KEY]"
#fdfdfdfsdafffdfs df dsfwrt rteth
name="John Doe"
email="john.doe@example.com"
# This is a comment line
age=30  
country="USA"
# Another comment here
occupation="Software Engineer"
password="P@ssw0rd123"
